# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitUtil < Formula
  desc "A command-line utility tool for common Git operations."
  homepage "https://github.com/OmSingh2003/git-util"
  version "0.1.1"

  on_macos do
    url "https://github.com/OmSingh2003/git-util/releases/download/v0.1.1/git-util_0.1.1_darwin_amd64.tar.gz"
    sha256 "4e5615f4cd678881bf4327f5f19213fb1bb82d424277e9f7cf9ff74e27fe9b50"

    def install
      bin.install "git-util"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the GitUtil
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/OmSingh2003/git-util/releases/download/v0.1.1/git-util_0.1.1_linux_amd64.tar.gz"
        sha256 "c31559e9a6059e9e3658e24c9b80bba06411227116a38688f80f692b7d965169"

        def install
          bin.install "git-util"
        end
      end
    end
  end

  test do
    system "#{bin}/git-util version"
  end
end
