# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitUtil < Formula
  desc "A command-line utility tool for common Git operations."
  homepage "https://github.com/OmSingh2003/git-util"
  version "0.1.0"

  on_macos do
    url "https://github.com/OmSingh2003/git-util/releases/download/v0.1.0/git-util_0.1.0_darwin_amd64.tar.gz"
    sha256 "134ae9893c7d7570ccf6ebcdb39f7c98087f1322b63b60e2124928c206e007d6"

    def install
      bin.install "git-util"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the GitUtil
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/OmSingh2003/git-util/releases/download/v0.1.0/git-util_0.1.0_linux_amd64.tar.gz"
        sha256 "2effcedb72b0fecbaa84432bd3b5adbb35ae04dd2e769796c457018133900080"

        def install
          bin.install "git-util"
        end
      end
    end
  end
end
